name: Combined CI

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: All tests
    runs-on: ubuntu-latest
    environment: Default
    steps:

      #
      #     Setting up environment
      #
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      #
      #     Building Backend etc
      #

      - name: Build & Test Backend
        run: |
          go get -v -t -d ./...
          go build -v .
          go test -v  ./...
        working-directory: './'